[package]
name = "pihex"
version = "0.1.0"
authors = ["Lucas Allison"]
description = "Compute the nth hexadecimal digit of pi."
license = "MIT/Apache-2.0"
repository = "TODO"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
